import { useEffect, useState } from "react";

/**
 * Automated Compliance Assessment Report component.
 *
 * Fetches /compliance/compliance-report.json at runtime and renders:
 * - Overall score banner with framework breakdown
 * - Per-control status with evidence (file:line) and framework mappings
 * - Dependency issues (unpinned versions)
 * - Download link for the PDF (/compliance/compliance-report.pdf)
 *
 * The report is generated by scripts/compliance-scan.mjs which scans the
 * actual Primebrick source code for security-relevant patterns and maps
 * them to ISO 27001, NIS2, GDPR, CCPA, and OWASP frameworks.
 *
 * Styling uses Zudoku CSS theme variables so the component adapts to
 * light/dark mode automatically.
 */

interface Evidence {
  repo: string;
  file: string;
  line: number;
  snippet: string;
}

interface Control {
  id: string;
  title: string;
  description: string;
  severity: string;
  frameworks: Record<string, string>;
  status: string;
  evidenceCount: number;
  violationCount: number;
  reposScanned: string[];
  evidence: Evidence[];
  violations: Evidence[];
}

interface FrameworkScore {
  totalControls: number;
  compliant: number;
  partiallyCompliant: number;
  notFound: number;
  nonCompliant: number;
  score: number;
}

interface ComplianceReport {
  scanDate: string;
  scannerVersion: string;
  reposScanned: string[];
  overallScore: number;
  frameworkScores: Record<string, FrameworkScore>;
  controls: Control[];
  dependencies: Record<string, Array<{ package: string; version: string; severity: string; type: string; description: string }>>;
  summary: {
    totalControls: number;
    compliant: number;
    partiallyCompliant: number;
    notFound: number;
    nonCompliant: number;
    totalEvidence: number;
    totalViolations: number;
    unpinnedDependencies: number;
  };
}

const STATUS_COLORS: Record<string, string> = {
  "compliant": "#16a34a",
  "partially-compliant": "#ca8a04",
  "non-compliant": "#dc2626",
  "not-found": "#6b7280",
};

const STATUS_LABELS: Record<string, string> = {
  "compliant": "Compliant",
  "partially-compliant": "Partially",
  "non-compliant": "Non-Compliant",
  "not-found": "Not Found",
};

const SEVERITY_COLORS: Record<string, string> = {
  "critical": "#dc2626",
  "high": "#ea580c",
  "medium": "#ca8a04",
  "low": "#6b7280",
};

function ScoreBar({ score }: { score: number }) {
  const color = score >= 80 ? "#16a34a" : score >= 60 ? "#ca8a04" : "#dc2626";
  return (
    <div style={{ width: "100%", height: "8px", borderRadius: "4px", backgroundColor: "var(--muted)", overflow: "hidden" }}>
      <div style={{ width: `${score}%`, height: "100%", borderRadius: "4px", backgroundColor: color, transition: "width 0.3s" }} />
    </div>
  );
}

export default function ComplianceReportComponent() {
  const [report, setReport] = useState<ComplianceReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expandedControl, setExpandedControl] = useState<string | null>(null);

  useEffect(() => {
    fetch("/compliance/compliance-report.json")
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: ComplianceReport) => setReport(data))
      .catch((err: Error) => setError(err.message));
  }, []);

  if (error) {
    return (
      <div style={{ padding: "2rem", borderRadius: "var(--radius)", border: "1px solid var(--border)", backgroundColor: "var(--card)" }}>
        <p style={{ margin: 0, color: "var(--foreground)" }}>
          <strong>Compliance report not available.</strong>
        </p>
        <p style={{ margin: "0.5rem 0 0", fontSize: "0.85em", color: "var(--muted-foreground)" }}>
          The automated compliance scanner has not been run yet. The report is generated during the CI build process.
        </p>
      </div>
    );
  }

  if (!report) {
    return (
      <div style={{ padding: "2rem", textAlign: "center", color: "var(--muted-foreground)" }}>
        Loading compliance report...
      </div>
    );
  }

  const scanDate = new Date(report.scanDate).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  return (
    <div>
      {/* Download banner */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "1rem 1.5rem",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius)",
          backgroundColor: "var(--card)",
          marginBottom: "2rem",
          flexWrap: "wrap",
          gap: "1rem",
        }}
      >
        <div>
          <p style={{ margin: 0, fontWeight: 600, color: "var(--foreground)" }}>
            Automated Compliance Assessment — Primebrick v3
          </p>
          <p style={{ margin: "0.25rem 0 0", fontSize: "0.85em", color: "var(--muted-foreground)" }}>
            Scan date: {scanDate} · Scanner v{report.scannerVersion} · {report.reposScanned.length} repos · {report.summary.totalEvidence} evidence items
          </p>
        </div>
        <a
          href="/compliance/compliance-report.pdf"
          download
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "0.5rem",
            padding: "0.5rem 1rem",
            backgroundImage: "linear-gradient(to bottom right, #38bdf8, #818cf8)",
            color: "#ffffff",
            textDecoration: "none",
            borderRadius: "calc(var(--radius) - 0.125rem)",
            fontWeight: 600,
            fontSize: "0.9em",
          }}
        >
          ⬇ Download PDF Report
        </a>
      </div>

      {/* Overall score */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "2rem",
          padding: "1.5rem",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius)",
          backgroundColor: "var(--card)",
          marginBottom: "2rem",
          flexWrap: "wrap",
        }}
      >
        <div style={{ textAlign: "center" }}>
          <div style={{
            fontSize: "2.5rem",
            fontWeight: 700,
            color: report.overallScore >= 80 ? "#16a34a" : report.overallScore >= 60 ? "#ca8a04" : "#dc2626",
          }}>
            {report.overallScore}%
          </div>
          <div style={{ fontSize: "0.8em", color: "var(--muted-foreground)" }}>Overall Score</div>
        </div>
        <div style={{ flex: 1, minWidth: "200px" }}>
          <div style={{ display: "flex", gap: "1rem", flexWrap: "wrap", fontSize: "0.85em" }}>
            <span style={{ color: STATUS_COLORS["compliant"] }}>● {report.summary.compliant} compliant</span>
            <span style={{ color: STATUS_COLORS["partially-compliant"] }}>● {report.summary.partiallyCompliant} partial</span>
            <span style={{ color: STATUS_COLORS["not-found"] }}>● {report.summary.notFound} not found</span>
            {report.summary.nonCompliant > 0 && (
              <span style={{ color: STATUS_COLORS["non-compliant"] }}>● {report.summary.nonCompliant} non-compliant</span>
            )}
          </div>
          {report.summary.totalViolations > 0 && (
            <p style={{ margin: "0.5rem 0 0", fontSize: "0.8em", color: "#dc2626" }}>
              ⚠ {report.summary.totalViolations} violations detected
            </p>
          )}
          {report.summary.unpinnedDependencies > 0 && (
            <p style={{ margin: "0.25rem 0 0", fontSize: "0.8em", color: "#ca8a04" }}>
              ⚠ {report.summary.unpinnedDependencies} unpinned dependencies
            </p>
          )}
        </div>
      </div>

      {/* Framework scores */}
      <h3 style={{ fontSize: "1.1rem", fontWeight: 600, marginBottom: "0.75rem" }}>Framework Scores</h3>
      <div style={{ display: "grid", gap: "0.75rem", marginBottom: "2rem" }}>
        {Object.entries(report.frameworkScores).map(([name, s]) => (
          <div
            key={name}
            style={{
              padding: "0.75rem 1rem",
              border: "1px solid var(--border)",
              borderRadius: "calc(var(--radius) - 0.25rem)",
              backgroundColor: "var(--card)",
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.5rem" }}>
              <span style={{ fontWeight: 600, fontSize: "0.9rem" }}>{name}</span>
              <span style={{ fontWeight: 700, color: s.score >= 80 ? "#16a34a" : s.score >= 60 ? "#ca8a04" : "#dc2626" }}>
                {s.score}%
              </span>
            </div>
            <ScoreBar score={s.score} />
            <div style={{ fontSize: "0.75em", color: "var(--muted-foreground)", marginTop: "0.25rem" }}>
              {s.compliant} compliant · {s.partiallyCompliant} partial · {s.notFound} not found
              {s.nonCompliant > 0 && ` · ${s.nonCompliant} non-compliant`}
              {" · "}{s.totalControls} total controls
            </div>
          </div>
        ))}
      </div>

      {/* Control details */}
      <h3 style={{ fontSize: "1.1rem", fontWeight: 600, marginBottom: "0.75rem" }}>Control Assessment</h3>
      <div style={{ display: "grid", gap: "0.5rem" }}>
        {report.controls.map((control) => {
          const isExpanded = expandedControl === control.id;
          const statusColor = STATUS_COLORS[control.status] || "#6b7280";
          const sevColor = SEVERITY_COLORS[control.severity] || "#6b7280";
          return (
            <div
              key={control.id}
              style={{
                border: "1px solid var(--border)",
                borderRadius: "calc(var(--radius) - 0.25rem)",
                backgroundColor: "var(--card)",
                overflow: "hidden",
              }}
            >
              {/* Control header (clickable) */}
              <button
                onClick={() => setExpandedControl(isExpanded ? null : control.id)}
                style={{
                  width: "100%",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  padding: "0.75rem 1rem",
                  background: "none",
                  border: "none",
                  cursor: "pointer",
                  textAlign: "left",
                  color: "var(--foreground)",
                }}
              >
                <div>
                  <span style={{ fontWeight: 600, fontSize: "0.9rem" }}>{control.title}</span>
                  <span style={{ marginLeft: "0.5rem", fontSize: "0.7rem", color: sevColor, fontWeight: 600 }}>
                    [{control.severity.toUpperCase()}]
                  </span>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
                  <span style={{ fontSize: "0.75em", color: "var(--muted-foreground)" }}>
                    {control.evidenceCount} evidence
                  </span>
                  <span style={{
                    fontSize: "0.7rem",
                    fontWeight: 700,
                    color: statusColor,
                    textTransform: "uppercase",
                  }}>
                    {STATUS_LABELS[control.status] || control.status}
                  </span>
                  <span style={{ fontSize: "0.8em", color: "var(--muted-foreground)" }}>
                    {isExpanded ? "▼" : "▶"}
                  </span>
                </div>
              </button>

              {/* Expanded content */}
              {isExpanded && (
                <div style={{ padding: "0 1rem 0.75rem", borderTop: "1px solid var(--border)" }}>
                  <p style={{ margin: "0.5rem 0", fontSize: "0.85em", color: "var(--muted-foreground)" }}>
                    {control.description}
                  </p>
                  {/* Framework mappings */}
                  <div style={{ margin: "0.5rem 0", display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
                    {Object.entries(control.frameworks).map(([fw, ref]) => (
                      <span
                        key={fw}
                        style={{
                          fontSize: "0.7rem",
                          padding: "0.15rem 0.5rem",
                          borderRadius: "0.25rem",
                          backgroundColor: "var(--muted)",
                          color: "var(--muted-foreground)",
                        }}
                      >
                        {fw}: {ref}
                      </span>
                    ))}
                  </div>
                  {/* Repos scanned */}
                  <p style={{ margin: "0.5rem 0 0.25rem", fontSize: "0.75em", color: "var(--muted-foreground)" }}>
                    Scanned in: {control.reposScanned.join(", ")}
                  </p>
                  {/* Evidence */}
                  {control.evidence.length > 0 && (
                    <div style={{ marginTop: "0.5rem" }}>
                      <p style={{ margin: "0 0 0.25rem", fontSize: "0.75em", fontWeight: 600, color: "var(--foreground)" }}>
                        Evidence ({control.evidenceCount} total, showing first {control.evidence.length}):
                      </p>
                      {control.evidence.map((e, i) => (
                        <div
                          key={i}
                          style={{
                            fontSize: "0.72em",
                            color: "var(--muted-foreground)",
                            fontFamily: "monospace",
                            padding: "0.15rem 0 0.15rem 0.75rem",
                            borderLeft: "2px solid #16a34a",
                            marginBottom: "0.15rem",
                          }}
                        >
                          <span style={{ color: "var(--foreground)", fontWeight: 600 }}>
                            {e.repo}/{e.file}:{e.line}
                          </span>
                          {" — "}
                          {e.snippet}
                        </div>
                      ))}
                    </div>
                  )}
                  {/* Violations */}
                  {control.violations.length > 0 && (
                    <div style={{ marginTop: "0.5rem" }}>
                      <p style={{ margin: "0 0 0.25rem", fontSize: "0.75em", fontWeight: 600, color: "#dc2626" }}>
                        Violations ({control.violationCount} total, showing first {control.violations.length}):
                      </p>
                      {control.violations.map((v, i) => (
                        <div
                          key={i}
                          style={{
                            fontSize: "0.72em",
                            color: "var(--muted-foreground)",
                            fontFamily: "monospace",
                            padding: "0.15rem 0 0.15rem 0.75rem",
                            borderLeft: "2px solid #dc2626",
                            marginBottom: "0.15rem",
                          }}
                        >
                          <span style={{ color: "#dc2626", fontWeight: 600 }}>
                            {v.repo}/{v.file}:{v.line}
                          </span>
                          {" — "}
                          {v.snippet}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Dependency issues */}
      {Object.keys(report.dependencies).length > 0 && (
        <>
          <h3 style={{ fontSize: "1.1rem", fontWeight: 600, marginTop: "2rem", marginBottom: "0.75rem" }}>
            Dependency Issues
          </h3>
          <div style={{ display: "grid", gap: "0.5rem" }}>
            {Object.entries(report.dependencies).map(([repo, vulns]) => (
              <div
                key={repo}
                style={{
                  padding: "0.75rem 1rem",
                  border: "1px solid var(--border)",
                  borderRadius: "calc(var(--radius) - 0.25rem)",
                  backgroundColor: "var(--card)",
                }}
              >
                <p style={{ margin: 0, fontWeight: 600, fontSize: "0.9rem" }}>
                  {repo}: {vulns.length} unpinned dependencies
                </p>
                <ul style={{ margin: "0.5rem 0 0", paddingLeft: "1.5rem", fontSize: "0.8em", color: "var(--muted-foreground)" }}>
                  {vulns.slice(0, 10).map((v, i) => (
                    <li key={i}>
                      <code>{v.package}</code> — {v.description}
                    </li>
                  ))}
                  {vulns.length > 10 && <li>... and {vulns.length - 10} more</li>}
                </ul>
              </div>
            ))}
          </div>
        </>
      )}

      {/* Disclaimer */}
      <div style={{ marginTop: "2rem", padding: "1rem", borderRadius: "var(--radius)", backgroundColor: "var(--muted)", fontSize: "0.8em", color: "var(--muted-foreground)" }}>
        <strong>Disclaimer:</strong> This report is generated by an automated code pattern scanner.
        It detects the presence of security controls in the source code but does not constitute a
        formal compliance certification. Organizations should engage qualified auditors for official
        certification. The scanner maps code evidence to framework controls based on pattern matching —
        false positives and false negatives are possible.
      </div>
    </div>
  );
}
