#!/usr/bin/env node
/**
 * Generate navigation fragment from pages/ directory structure.
 * Scans pages/<repo>/{deepwiki,manual}/ for .md/.mdx files and
 * generates src/generated-nav.ts with a navigation array.
 *
 * Usage: node scripts/generate-nav.mjs
 * Run AFTER sync-repo-docs.mjs and sync-deepwiki.mjs
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const pagesDir = join(projectRoot, 'pages');

const REPOS = [
  { slug: 'backend', label: 'Backend', icon: 'server' },
  { slug: 'frontend', label: 'Frontend', icon: 'monitor' },
  { slug: 'microservices', label: 'Microservices', icon: 'boxes' },
  { slug: 'dal', label: 'DAL Library', icon: 'database' },
  { slug: 'sdk', label: 'SDK Library', icon: 'package' },
];

const SUBDIRS = ['deepwiki', 'manual'];

function extractTitle(filePath) {
  try {
    const content = readFileSync(filePath, 'utf-8');
    const fmMatch = content.match(/^---\n[\s\S]*?title:\s*["']?(.+?)["']?\s*$/m);
    if (fmMatch) return fmMatch[1];
    const h1Match = content.match(/^#\s+(.+)$/m);
    if (h1Match) return h1Match[1];
  } catch {}
  return null;
}

function scanDir(dir, basePath) {
  const items = [];
  if (!existsSync(dir)) return items;

  const entries = readdirSync(dir).sort();
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) continue;

    if (!entry.match(/\.(md|mdx)$/)) continue;

    const name = entry.replace(/\.(md|mdx)$/, '');
    if (name === 'index') continue; // index files are landing pages, handled separately

    const title = extractTitle(fullPath) || name.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    const relativePath = relative(pagesDir, fullPath).replace(/\\/g, '/').replace(/\.(md|mdx)$/, '');

    items.push({
      type: 'doc',
      file: relativePath,
      label: title,
    });
  }

  return items;
}

function buildRepoNav(repo) {
  const items = [];

  for (const subdir of SUBDIRS) {
    const dir = join(pagesDir, repo.slug, subdir);
    const docs = scanDir(dir, `${repo.slug}/${subdir}`);

    if (docs.length === 0) {
      // Keep the placeholder index if no synced content
      const indexPath = join(dir, 'index.mdx');
      if (existsSync(indexPath)) {
        items.push(`${repo.slug}/${subdir}/index`);
      }
      continue;
    }

    // Add synced docs
    items.push(...docs.map(d => d.file));
  }

  if (items.length === 0) {
    // Fallback: just point to the deepwiki index
    items.push(`${repo.slug}/deepwiki/index`);
  }

  return {
    type: 'category',
    label: repo.label,
    icon: repo.icon,
    collapsed: true,
    items,
  };
}

// Main
console.log('=== Generating navigation fragment ===');

const repoNavs = REPOS.map(buildRepoNav);

const output = `// AUTO-GENERATED by scripts/generate-nav.mjs — DO NOT EDIT
// Regenerated on each sync run in CI
import type { Navigation } from "zudoku";

export const generatedRepoNav: Navigation = ${JSON.stringify(repoNavs, null, 2)};

// Split for stacked navigation: Services (BE, FE, Microservices) + Libraries (DAL, SDK)
export const serviceNav: Navigation = ${JSON.stringify(repoNavs.slice(0, 3), null, 2)};
export const libraryNav: Navigation = ${JSON.stringify(repoNavs.slice(3), null, 2)};
`;

const outputPath = join(projectRoot, 'src', 'generated-nav.ts');
writeFileSync(outputPath, output, 'utf-8');
console.log(`Wrote ${outputPath}`);
console.log('=== Navigation generation complete ===');
