// AUTO-GENERATED by scripts/generate-nav.mjs — DO NOT EDIT
// Regenerated on each sync run in CI
import type { Navigation } from "zudoku";

export const generatedRepoNav: Navigation = [
  {
    "type": "category",
    "label": "Backend",
    "icon": "server",
    "collapsed": true,
    "items": [
      "backend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Frontend",
    "icon": "monitor",
    "collapsed": true,
    "items": [
      "frontend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Microservices",
    "icon": "boxes",
    "collapsed": true,
    "items": [
      "microservices/guide/overview",
      "microservices/guide/architecture",
      "microservices/guide/conventions",
      {
        "type": "category",
        "label": "Services",
        "items": [
          "microservices/guide/services/emailsender"
        ]
      }
    ]
  },
  {
    "type": "category",
    "label": "DAL Library",
    "icon": "database",
    "collapsed": true,
    "items": [
      "dal/guide/audit-trail",
      "dal/guide/clone",
      "dal/guide/api-reference",
      "dal/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "SDK Library",
    "icon": "package",
    "collapsed": true,
    "items": [
      "sdk/guide/overview",
      "sdk/guide/getting-started",
      "sdk/guide/authentication",
      "sdk/guide/ext-json",
      "sdk/guide/nats-client",
      "sdk/guide/service-registration",
      "sdk/guide/http-server",
      "sdk/guide/api-reference"
    ]
  }
];

// Split for stacked navigation: Services (BE, FE, Microservices) + Libraries (DAL, SDK)
export const serviceNav: Navigation = [
  {
    "type": "category",
    "label": "Backend",
    "icon": "server",
    "collapsed": true,
    "items": [
      "backend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Frontend",
    "icon": "monitor",
    "collapsed": true,
    "items": [
      "frontend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Microservices",
    "icon": "boxes",
    "collapsed": true,
    "items": [
      "microservices/guide/overview",
      "microservices/guide/architecture",
      "microservices/guide/conventions",
      {
        "type": "category",
        "label": "Services",
        "items": [
          "microservices/guide/services/emailsender"
        ]
      }
    ]
  }
];
export const libraryNav: Navigation = [
  {
    "type": "category",
    "label": "DAL Library",
    "icon": "database",
    "collapsed": true,
    "items": [
      "dal/guide/audit-trail",
      "dal/guide/clone",
      "dal/guide/api-reference",
      "dal/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "SDK Library",
    "icon": "package",
    "collapsed": true,
    "items": [
      "sdk/guide/overview",
      "sdk/guide/getting-started",
      "sdk/guide/authentication",
      "sdk/guide/ext-json",
      "sdk/guide/nats-client",
      "sdk/guide/service-registration",
      "sdk/guide/http-server",
      "sdk/guide/api-reference"
    ]
  }
];
