// AUTO-GENERATED by scripts/generate-nav.mjs — DO NOT EDIT
// Regenerated on each sync run in CI
import type { Navigation } from "zudoku";

export const generatedRepoNav: Navigation = [
  {
    "type": "category",
    "label": "Frontend",
    "icon": "monitor",
    "collapsed": true,
    "items": [
      "frontend/guide/overview",
      "frontend/guide/getting-started",
      "frontend/guide/ui-stack",
      "frontend/guide/app-shell",
      "frontend/guide/authentication",
      "frontend/guide/entity-list-table",
      "frontend/guide/settings",
      "frontend/guide/ui-components",
      {
        "type": "category",
        "label": "Components",
        "items": [
          "frontend/guide/components/combo-select",
          "frontend/guide/components/dynamic-icon",
          "frontend/guide/components/color-selector",
          "frontend/guide/components/avatar-preview",
          "frontend/guide/components/event-card",
          "frontend/guide/components/command-palette",
          "frontend/guide/components/app-shell",
          "frontend/guide/components/app-sidebar",
          "frontend/guide/components/app-topbar",
          "frontend/guide/components/app-page-layout",
          "frontend/guide/components/app-page-scaffold",
          "frontend/guide/components/app-page-breadcrumb",
          "frontend/guide/components/app-server-banner",
          "frontend/guide/components/browser-client-info",
          "frontend/guide/components/lang-select",
          "frontend/guide/components/theme-toggle",
          "frontend/guide/components/sidebar-health-badge",
          "frontend/guide/components/sidebar-module-switcher",
          "frontend/guide/components/sidebar-org-switcher",
          "frontend/guide/components/sidebar-profile-menu",
          "frontend/guide/components/sidebar-version-badge",
          "frontend/guide/components/button-async",
          "frontend/guide/components/form-page-layout",
          "frontend/guide/components/form-label-with-help",
          "frontend/guide/components/form-label-with-priority-help",
          "frontend/guide/components/password-checklist",
          "frontend/guide/components/choicebox",
          "frontend/guide/components/date-wheel-picker",
          "frontend/guide/components/event-toast",
          "frontend/guide/components/loading-bar",
          "frontend/guide/components/metadata-loading",
          "frontend/guide/components/json-table-viewer",
          "frontend/guide/components/dialog-bordered",
          "frontend/guide/components/rfc-error-dialog",
          "frontend/guide/components/login-form",
          "frontend/guide/components/passkey-button",
          "frontend/guide/components/passkey-enrollment",
          "frontend/guide/components/passkey-prompt-dialog",
          "frontend/guide/components/session-expired-dialog",
          "frontend/guide/components/input",
          "frontend/guide/components/tooltip",
          "frontend/guide/components/form"
        ]
      },
      "frontend/guide/api-reference"
    ]
  },
  {
    "type": "category",
    "label": "Microservices",
    "icon": "boxes",
    "collapsed": true,
    "items": [
      "microservices/guide/overview",
      "microservices/guide/architecture",
      "microservices/guide/conventions",
      {
        "type": "category",
        "label": "Services",
        "items": [
          "microservices/guide/services/emailsender"
        ]
      }
    ]
  },
  {
    "type": "category",
    "label": "DAL Library",
    "icon": "database",
    "collapsed": true,
    "items": [
      "dal/guide/audit-trail",
      "dal/guide/clone",
      "dal/guide/api-reference"
    ]
  },
  {
    "type": "category",
    "label": "SDK Library",
    "icon": "package",
    "collapsed": true,
    "items": [
      "sdk/guide/overview",
      "sdk/guide/getting-started",
      "sdk/guide/authentication",
      "sdk/guide/ext-json",
      "sdk/guide/nats-client",
      "sdk/guide/service-registration",
      "sdk/guide/http-server",
      "sdk/guide/api-reference"
    ]
  }
];

// Split for stacked navigation: Services (BE, FE, Microservices) + Libraries (DAL, SDK)
export const serviceNav: Navigation = [
  {
    "type": "category",
    "label": "Frontend",
    "icon": "monitor",
    "collapsed": true,
    "items": [
      "frontend/guide/overview",
      "frontend/guide/getting-started",
      "frontend/guide/ui-stack",
      "frontend/guide/app-shell",
      "frontend/guide/authentication",
      "frontend/guide/entity-list-table",
      "frontend/guide/settings",
      "frontend/guide/ui-components",
      {
        "type": "category",
        "label": "Components",
        "items": [
          "frontend/guide/components/combo-select",
          "frontend/guide/components/dynamic-icon",
          "frontend/guide/components/color-selector",
          "frontend/guide/components/avatar-preview",
          "frontend/guide/components/event-card",
          "frontend/guide/components/command-palette",
          "frontend/guide/components/app-shell",
          "frontend/guide/components/app-sidebar",
          "frontend/guide/components/app-topbar",
          "frontend/guide/components/app-page-layout",
          "frontend/guide/components/app-page-scaffold",
          "frontend/guide/components/app-page-breadcrumb",
          "frontend/guide/components/app-server-banner",
          "frontend/guide/components/browser-client-info",
          "frontend/guide/components/lang-select",
          "frontend/guide/components/theme-toggle",
          "frontend/guide/components/sidebar-health-badge",
          "frontend/guide/components/sidebar-module-switcher",
          "frontend/guide/components/sidebar-org-switcher",
          "frontend/guide/components/sidebar-profile-menu",
          "frontend/guide/components/sidebar-version-badge",
          "frontend/guide/components/button-async",
          "frontend/guide/components/form-page-layout",
          "frontend/guide/components/form-label-with-help",
          "frontend/guide/components/form-label-with-priority-help",
          "frontend/guide/components/password-checklist",
          "frontend/guide/components/choicebox",
          "frontend/guide/components/date-wheel-picker",
          "frontend/guide/components/event-toast",
          "frontend/guide/components/loading-bar",
          "frontend/guide/components/metadata-loading",
          "frontend/guide/components/json-table-viewer",
          "frontend/guide/components/dialog-bordered",
          "frontend/guide/components/rfc-error-dialog",
          "frontend/guide/components/login-form",
          "frontend/guide/components/passkey-button",
          "frontend/guide/components/passkey-enrollment",
          "frontend/guide/components/passkey-prompt-dialog",
          "frontend/guide/components/session-expired-dialog",
          "frontend/guide/components/input",
          "frontend/guide/components/tooltip",
          "frontend/guide/components/form"
        ]
      },
      "frontend/guide/api-reference"
    ]
  },
  {
    "type": "category",
    "label": "Microservices",
    "icon": "boxes",
    "collapsed": true,
    "items": [
      "microservices/guide/overview",
      "microservices/guide/architecture",
      "microservices/guide/conventions",
      {
        "type": "category",
        "label": "Services",
        "items": [
          "microservices/guide/services/emailsender"
        ]
      }
    ]
  },
  {
    "type": "category",
    "label": "DAL Library",
    "icon": "database",
    "collapsed": true,
    "items": [
      "dal/guide/audit-trail",
      "dal/guide/clone",
      "dal/guide/api-reference"
    ]
  }
];
export const libraryNav: Navigation = [
  {
    "type": "category",
    "label": "SDK Library",
    "icon": "package",
    "collapsed": true,
    "items": [
      "sdk/guide/overview",
      "sdk/guide/getting-started",
      "sdk/guide/authentication",
      "sdk/guide/ext-json",
      "sdk/guide/nats-client",
      "sdk/guide/service-registration",
      "sdk/guide/http-server",
      "sdk/guide/api-reference"
    ]
  }
];
