// AUTO-GENERATED by scripts/generate-nav.mjs — DO NOT EDIT
// Regenerated on each sync run in CI
import type { Navigation } from "zudoku";

export const generatedRepoNav: Navigation = [
  {
    "type": "category",
    "label": "Backend",
    "icon": "server",
    "collapsed": true,
    "items": [
      "backend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Frontend",
    "icon": "monitor",
    "collapsed": true,
    "items": [
      "frontend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Microservices",
    "icon": "boxes",
    "collapsed": true,
    "items": [
      "microservices/guide/index"
    ]
  },
  {
    "type": "category",
    "label": "DAL Library",
    "icon": "database",
    "collapsed": true,
    "items": [
      "dal/guide/index"
    ]
  },
  {
    "type": "category",
    "label": "SDK Library",
    "icon": "package",
    "collapsed": true,
    "items": [
      "sdk/guide/api-reference"
    ]
  }
];

// Split for stacked navigation: Services (BE, FE, Microservices) + Libraries (DAL, SDK)
export const serviceNav: Navigation = [
  {
    "type": "category",
    "label": "Backend",
    "icon": "server",
    "collapsed": true,
    "items": [
      "backend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Frontend",
    "icon": "monitor",
    "collapsed": true,
    "items": [
      "frontend/guide/overview"
    ]
  },
  {
    "type": "category",
    "label": "Microservices",
    "icon": "boxes",
    "collapsed": true,
    "items": [
      "microservices/guide/index"
    ]
  }
];
export const libraryNav: Navigation = [
  {
    "type": "category",
    "label": "DAL Library",
    "icon": "database",
    "collapsed": true,
    "items": [
      "dal/guide/index"
    ]
  },
  {
    "type": "category",
    "label": "SDK Library",
    "icon": "package",
    "collapsed": true,
    "items": [
      "sdk/guide/api-reference"
    ]
  }
];
