// AUTO-GENERATED by scripts/fetch-openapi.mjs — DO NOT EDIT MANUALLY.
// Regenerated on every build via: node scripts/fetch-openapi.mjs

import type { ZudokuConfig } from "zudoku";

export const generatedApis: ZudokuConfig["apis"] = [
  {
    type: "file",
    input: "./apis/system.json",
    path: "/catalog/system",
    options: {
      disableSecurity: false,
      expandAllTags: true,
      showInfoPage: true,
      examplesLanguage: "js",
      schemaDownload: {
        enabled: true,
        fileName: "primebrick-system",
      },
    },
    categories: [
          {
                "label": "System Brick",
                "tags": [
                      "Backend",
                      "Core"
                ]
          }
    ],
  },
];
